- hosts: all
  tasks:
  - name: install fail2ban package
    apt: pkg=fail2ban state=present
    when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'
    become: yes

  - name: copy fail2ban local config
    copy: src=jail.local dest=/etc/fail2ban/jail.local owner=root group=root mode=0644
    become: yes
    notify: restart fail2ban

  - name: Secured sshd config
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication yes" }
      - { regexp: "^UsePAM", line: "UsePAM yes" }
      - { regexp: "^AuthenticationMethods", line: "AuthenticationMethods publickey" }
      - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
      - { regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no" }
      - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
      - { regexp: "^PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    notify: restart ssh

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted
